version: '3.8'

services:
  cv:
    build: .
    container_name: cv
    networks:
      - app-network
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
